default[:letsencrypt][:ppa_path] = 'ppa:certbot/certbot'
default[:letsencrypt][:config_dir] = '/etc/letsencrypt'
default[:letsencrypt][:opsworks_region] = 'us-east-1'
default[:letsencrypt][:s3_backup_region] = 'us-east-1'
default[:letsencrypt][:scripts_path] = '/home/ubuntu'
